services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dateCountUp
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
